##配置项目名称
spring:
  application:
    name: stream-server
  cloud:
    stream:
      bindings:
        input:
          group: bill
          destination: input-bill
        output:
          destination: output-bill
  rabbitmq:
    host: 120.78.129.142
    port: 5672
    username: hugui
    password: hugui123

##配置项目访问端口
server:
  port: 5001