server:
  port: 3001

spring:
  application:
    name: front-web
  cloud:
    stream:
      bindings:
        add_user_output:
          destination: add_user_queue
          group: add_user
  rabbitmq:
    host: 120.78.129.142
    port: 5672
    username: hugui
    password: hugui123

eureka:
  client:
    serviceUrl:
      defaultZone: http://hugui:admin@127.0.0.1:1001/eureka


##开启ribbon client的饥饿加载模式
ribbon:
  eager-load:
    enabled: true
    clients:
      user

