server:
  port: 3001

spring:
  application:
    name: user-web

eureka:
  client:
    serviceUrl:
      defaultZone: http://hugui:admin@127.0.0.1:1001/eureka


##开启ribbon client的饥饿加载模式
ribbon:
  eager-load:
    enabled: true
    clients:
      user

